src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


#[ORM\Entity(repositoryClass: RecipeRepository::class)]
//pas avoir les recettes avec le meme nom
#[UniqueEntity('name')]
#[ORM\HasLifecycleCallbacks]
#[Vich\Uploadable]
class Recipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 50)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 50)]
    private ?string $name = null;

    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'recipes_images', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Positive()]
    #[Assert\LessThan(1441)]
    private ?int $time = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Positive()]
    #[Assert\LessThan(51)]
    private ?int $person_nb = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Positive()]
    #[Assert\LessThan(6)]
    private ?int $difficulty = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Positive()]
    #[Assert\LessThan(1001)]
    private ?float $price = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isFavorite = null;

    #[ORM\Column]
    private ?bool $isPublic = false;

    #[ORM\Column(nullable: true)]
    #[Assert\NotNull]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    #[Assert\NotNull()]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToMany(targetEntity: Ingredient::class)]
    private Collection $ingredients;

    #[ORM\ManyToOne(inversedBy: 'recipes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'recipe', targetEntity: Rating::class, orphanRemoval: true)]
    private Collection $ratings;

    private ?float $average = null;

    //pour chaque collection des ingredients on va initialiser au moment de sa creation on va egalement obtenir 2 dates, creation et modification
    public function __construct()
    {
        $this->ingredients = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable;
        $this->updatedAt = new \DateTimeImmutable();
        $this->ratings = new ArrayCollection();
    }
    //va remplir un attribut avant que l'entité soit persistée
    #[ORM\PrePersist()]
    //il faut lui rajouter un cycle de vie sinon ne fonctionne pas : ORM/HasLifeCycleCallBack
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;
        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getTime(): ?int
    {
        return $this->time;
    }

    public function setTime(?int $time): static
    {
        $this->time = $time;

        return $this;
    }

    public function getPersonNb(): ?int
    {
        return $this->person_nb;
    }

    public function setPersonNb(?int $person_nb): static
    {
        $this->person_nb = $person_nb;

        return $this;
    }

    public function getDifficulty(): ?int
    {
        return $this->difficulty;
    }

    public function setDifficulty(?int $difficulty): static
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getIsFavorite(): ?bool
    {
        return $this->isFavorite;
    }

    public function setIsFavorite(?bool $isFavorite): static
    {
        $this->isFavorite = $isFavorite;

        return $this;
    }
    public function getIsPublic(): ?bool
    {
        return $this->isPublic;
    }
    public function setIsPublic(bool $isPublic): static
    {
        $this->isPublic = $isPublic;

        return $this;
    }
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Ingredient>
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }

    public function addIngredient(Ingredient $ingredient): static
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients->add($ingredient);
        }

        return $this;
    }

    public function removeIngredient(Ingredient $ingredient): static
    {
        $this->ingredients->removeElement($ingredient);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Rating>
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Rating $rating): static
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings->add($rating);
            $rating->setRecipe($this);
        }

        return $this;
    }

    public function removeRating(Rating $rating): static
    {
        if ($this->ratings->removeElement($rating)) {
            // set the owning side to null (unless already changed)
            if ($rating->getRecipe() === $this) {
                $rating->setRecipe(null);
            }
        }

        return $this;
    }
    /**
     * Get the value of average, calcul d'une moyenne
     */
    public function getAverage()
    {
        $ratings = $this->ratings;
        if ($ratings->toArray() === []) {
            return null;
        }
        $total = 0;
        foreach ($ratings as $rating) {
            $total += $rating->getRate();
        }
        return $this->average = $total / count($ratings);
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Rating;
use App\Entity\Recipe;
use App\Form\RatingType;
use App\Form\RecipeType;
use App\Repository\RatingRepository;
use App\Repository\RecipeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class RecipeController extends AbstractController
{
    /**
     * method fetch all (READ)
     *
     * @param PaginatorInterface $paginator
     * @param RecipeRepository $recipeRepository
     * @param Request $request
     * @return Response
     */
    #[Route('/recipes', name: 'app_recipes', methods: ['GET'])]
    #[IsGranted('ACCES_PAGES')]

    public function findAllRecipes(
        PaginatorInterface $paginator,
        RecipeRepository $recipeRepository,
        Request $request
    ): Response {
        $recipes = $paginator->paginate(
            //methode comprend query et request
            $recipeRepository->findBy(['user' => $this->getUser()]), /* $query */
            $request->query->getInt('page', 1), /*page number*/
            5 /*limit par page*/
        );
        return $this->render(
            'content/recipe/index.html.twig',
            [
                'recipes' => $recipes
            ]
        );
    }
    /**
     * methode render public(parser)
     *
     * @return boolean
     */
    #[Security("is_granted('ACCES_PAGES') && (recipe.getIsPublic() === true || user === recipe.getUser())")]
    #[Route('recipe/{id}', name: 'show_recipe', methods: ['GET', 'POST'])]
    public function isPublic(
        Recipe $recipe,
        RatingRepository $ratingRepository,
        EntityManagerInterface $manager,
        Request $request
    ): Response {
        $rating = new Rating();
        $form = $this->createForm(RatingType::class, $rating);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $rating->setUser($this->getUser())
                ->setRecipe($recipe);

            //utilisateur ne doit pas pouvoir faire 2 fois la notation
            //la repository va chercher dans la table rating id de la recette et l'id d'utilisateur. Si les deux existent, c'est que cet user a déjà noté la recette en question. si non, il peut la noter
            $ratingInData = $ratingRepository->findOneBy([
                'user' => $this->getUser(),
                'recipe' => $recipe
            ]);

            if (!$ratingInData) {
                $manager->persist($rating);
            } else {
                $ratingInData->setRate(
                    $form->getData()->getRate()
                );
            }
            $manager->flush();
            $this->addFlash(
                "success",
                "Merci, Votre note a bien été ajouté ! "
            );
            return $this->redirectToRoute('show_recipe', ['id' => $recipe->getId()]);
        }

        return $this->render(
            'content/recipe/show.html.twig',
            [
                'recipe' => $recipe,
                'form' => $form->createView()
            ]
        );
    }

    #[Route('recipes/public', name: 'public_recipes', methods: 'GET')]
    public function repositoryPublic(
        PaginatorInterface $paginator,
        RecipeRepository $repository,
        Request $request
    ): Response {
        $public_recipes = $paginator->paginate(
            $repository->findPublicRecipe(50),
            $request->query->getInt('page', 1),
            7
        );
        return $this->render(
            'content/recipe/public_recipes.html.twig',
            ['public_recipes' => $public_recipes]
        );
    }
    /**
     * method CREATE
     *
     * @param RecipeRepository $recipeRepository
     * @param integer $id
     * @return Response
     */
    #[IsGranted('ACCES_PAGES')]
    #[Route('/recipes/create', name: 'new_recipe', methods: ['GET', 'POST'])]
    public function createNewRecipe(
        Request $request,
        EntityManagerInterface $manager
    ): Response {

        $recipe = new Recipe();
        //aller creer Formulaire; creation de Type dans bin/console make form
        $form = $this->createForm(RecipeType::class, $recipe);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // dd($form->getData());
            $recipe = $form->getData();
            $recipe->setUser($this->getUser());
            $manager->persist($recipe);
            $manager->flush();
            $this->addFlash(
                "success",
                "Votre recette a bien été crée. "
            );

            return $this->redirectToRoute('app_recipes');
        }

        return $this->render(
            'content/recipe/new.html.twig',
            [
                'form' => $form->createView()
            ]
        );
    }

    /**
     * method UPDATE
     *
     * @param EntityManagerInterface $manager
     * @param RecipeRepository $repository
     * @param Request $request
     * @param integer $id
     * @return Response
     */
    #[Security("is_granted('ACCES_PAGES') and user === recipe.getUser() ")]
    #[Route(path: '/recipes/edit/{id}', name: 'edit_recipe', methods: ['GET', 'POST'])]
    public function editRecipe(
        EntityManagerInterface $manager,
        RecipeRepository $repository,
        Request $request,
        int $id,
        Recipe $recipe
    ): Response {
        $recipe = $repository->find($id);
        $form = $this->createForm(RecipeType::class, $recipe);
        //fait apparraitre les données dans le formumlaire
        $form->handleRequest($request);
        //2 etape validation de formulaire; il enverra les données du formulaire dans la bdd
        $recipe = $form->getData();

        if ($form->isSubmitted() && $form->isValid()) {
            $manager->persist($recipe);
            // ce message se rajoutera aux changements
            $manager->flush();
            $this->addFlash(
                "success",
                "yeah, New recipe added in the list. "
            );
            return $this->redirectToRoute('app_recipes');
        }
        //1 etape - retourner la vue edit.html.twig; la vue appellera la variable(clé) 'form' et cette dernière creera un formulaire
        return $this->render(
            'content/recipe/edit.html.twig',
            [
                'form' => $form->createView()
            ]
        );
    }
    /**
     * handleRequest est une étape dans le cycle de vie du formulaire Symfony. Elle prend les données de la requête, les lie au formulaire, effectue la validation et met à jour l'état du formulaire. Cela permet de préparer le formulaire pour être utilisé dans le contrôleur, par exemple, pour effectuer des actions basées sur les données soumises par l'utilisateur.
     */

    /**
     * DELETE function
     * @param EntityManagerInterface $manager
     * @param RecipeRepository $recipeRepository
     * @param integer $id
     * @return Response
     */
    #[Route('recipes/delete/{id}', name: 'delete_recipe', methods: ['GET'])]
    public function deleteRecipe(
        EntityManagerInterface $manager,
        RecipeRepository $recipeRepository,
        int $id
    ): Response {
        $recipe = $recipeRepository->find($id);
        //si n'existe pas, afficher un message et rediriger
        if (!$recipe) {
            $this->addFlash(
                'danger',
                'Recipe doesn\'t exist'
            );
            return $this->redirectToRoute('app_recipes');
        }
        //sinon supprimer
        $manager->remove($recipe);
        $manager->flush();
        $this->addFlash(
            'danger',
            'Recipe ' . $id . ' is deleted !'
        );
        return $this->redirectToRoute('app_recipes');
    }
}

templates/content/recipe/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Change Recipe
{% endblock %}

{% block body %}
	<div class="container">
		<h2 class='mt-4' style="color: #4F805D">Change Recipe</h2>
		<div class="form-group">
			{{ form_start(form) }}
			<div class="row">
				{{ form_label(form.name) }}
				{{ form_widget(form.name) }}
				<div class="form-error">
					{{ form_errors(form.name) }}
				</div>
			</div>
			<div class="col">
				{{ form_label(form.time) }}
				{{ form_widget(form.time) }}
				<div class="error">
					{{ form_errors(form.time) }}
				</div>
			</div>
			<div class="col">
				{{ form_label(form.person_nb) }}
				{{ form_widget(form.person_nb) }}
				<div class="error">
					{{ form_errors(form.person_nb) }}
				</div>
			</div>
			<div class="col">
				{{ form_label(form.difficulty) }}
				{{ form_widget(form.difficulty) }}
				<div class="error">
					{{ form_errors(form.difficulty) }}
				</div>
			</div>
			<div class="col">
				{{ form_label(form.description) }}
				{{ form_widget(form.description) }}
				<div class="error">
					{{ form_errors(form.description) }}
				</div>
			</div>
			<div class="col mt-4">
				{{ form_label(form.price) }}
				{{ form_widget(form.price) }}
				<div class="error">
					{{ form_errors(form.price) }}
				</div>
			</div>
			<div class="form-check mt-4">
				{{ form_label(form.isFavorite) }}
				{{ form_widget(form.isFavorite) }}
				<div class="error">
					{{ form_errors(form.isFavorite) }}
				</div>
			</div>
			<div class="col mt-4">
				{{ form_label(form.ingredients) }}
				{{ form_widget(form.ingredients) }}
				<div class="error">
					{{ form_errors(form.ingredients) }}
				</div>
			</div>
			<div class="row">
				{{ form_row(form.submit) }}
			</div>
		</div>
		{{ form_end(form) }}
	</div>
</div>{% endblock %}

templates/content/recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Our Recipes
{% endblock %}

{% block body %}

	<div class='container mt-3'>

		<div class="container mt-5 text-center">
			{% for label, messages in app.flashes %}
				{% for message in messages %}
					<div class="alert alert-success mt-4">
						{{ message }}
					</div>
				{% endfor %}
			{% endfor %}

			{% if not recipes.items is same as([]) %}
				<h4 style="color: #4F805D">All recipes :</h4>
				<button class="mb-4 btn btn-primary">
					<a href={{ path('new_recipe')}}>
						Create a new recipe
					</a>
				</button>

				{# pour afficher un message de rajout d'un ingredient #}
				{% for label, messages in app.flashes %}
					{% for message in messages %}
						<div class="alert alert-success mt-4">
							{{ message }}
						</div>
					{% endfor %}
				{% endfor %}
				{# getTotalItemCount methode symf pour compter le nombre total des objets  #}
				<p class='mb-2'>
					{{ recipes.getTotalItemCount }}
					total recipes :
				</p>
				<table class="table table-active">
					<thead class="thead table-info">
						<tr>
							<th scope="col">ID</th>
							<th scope="col">Name</th>
							<th scope="col">Difficulty</th>
							<th scope="col">Description</th>
							<th scope="col">Price</th>
							<th scope="col">created</th>
							<th scope="col">Edit</th>
							<th scope="col">Delete</th>
						</tr>
					</thead>
					<tbody>
						{# comme plusieurs criteres ne sont pas renseignées, on rajoute des ternary pour twig #}
						{% for recipe in recipes %}
							<tr class="table-light">
								<th scope="row">
									<p>
										{{ recipe.id }}
									</p>
								</th>
								<td>
									<p>
										{{ recipe.name }}
									</p>
								</td>
								<td>
									<p>
										{# si la valeur n'existe pas, afficher le text suivant, sinon afficher la valeur #}
										{{ (recipe.difficulty == null) ? '--' : recipe.difficulty }}
									</p>
								</td>
								<td>
									<p>
										{{ recipe.description }}
									</p>
								</td>
								<td>
									<p>
										{{ (recipe.price is same as(null)) ? 'No info yet' : recipe.price }}
									</p>
								</td>
								<td>
									<p>
										{{ recipe.createdAt|date('d/m/Y') }}
									</p>
								</td>
								<td>
									<button class="btn btn-warning">
										<a href="{{ path('edit_recipe', { id: recipe.id }) }}">
											EDIT
										</a>
									</button>
								</td>
								<td>
									<button class="btn btn-danger">
										<a href="{{ path('delete_recipe', { id: recipe.id }) }}">
											DELETE
										</a>
									</a>
								</td>
							</tr>
						</button>
					</tbody>
				</td>
			</tr>
		{% endfor %}
	</tbody>
</table>{# display navigation #}<div class="navigation d-flex justify-content-center mt-4">
	{{ knp_pagination_render(recipes) }}</div>{% else %}
<h4>No recipes</h4>
<a href="{{ path('new_recipe')}}">
	<h5>
		Create a new recipe
	</h5>
</a>{% endif %}{% endblock %}

templates/content/recipe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	New Recipe
{% endblock %}

{% block body %}
	<div class="container">
		<h2 class='mt-4' style="color: #4F805D">Create your recipe</h2>
		<div class="form-group">
			{{ form_start(form) }}
			{#form customisé doc/current/form/form_customization.html #}
			{# <div class="col">
								{{ form_label(form.name) }}
								{{ form_widget(form.name) }}
								<div class="form-error">
									{{ form_errors(form.name) }}
								</div>
							</div>
							<div class="col">
								{{ form_label(form.time) }}
								{{ form_widget(form.time) }}
								<div class="error">
									{{ form_errors(form.time) }}
								</div>
							</div>
							<div class="col">
								{{ form_label(form.person_nb) }}
								{{ form_widget(form.person_nb) }}
								<div class="error">
									{{ form_errors(form.person_nb) }}
								</div>
							</div>
			                <div class="col">
								{{ form_label(form.difficulty) }}
								{{ form_widget(form.difficulty) }}
								<div class="error">
									{{ form_errors(form.difficulty) }}
								</div>
							</div>
			                <div class="col">
								{{ form_label(form.description) }}
								{{ form_widget(form.description) }}
								<div class="error">
									{{ form_errors(form.description) }}
								</div>
							</div>
			                <div class="col">
								{{ form_label(form.price) }}
								{{ form_widget(form.price) }}
								<div class="error">
									{{ form_errors(form.price) }}
								</div>
							</div>
			                <div class="col">
								{{ form_label(form.isFavorite) }}
								{{ form_widget(form.isFavorite) }}
								<div class="error">
									{{ form_errors(form.isFavorite) }}
								</div>
							</div>
			                <div class="col">
								{{ form_label(form.ingredients) }}
								{{ form_widget(form.ingredients) }}
								<div class="error">
									{{ form_errors(form.ingredients) }}
								</div>
							</div>
							<div class="row">
								{{ form_row(form.submit) }}
							</div>
						</div> #}
		{{ form_end(form) }}
	</div>
		{#helper function to render the form content#}
	{% endblock %}

templates/content/recipe/public_recipes.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Our Recipes
{% endblock %}

{% block body %}

	<div class='container mt-4 text-center'>
		{% if not public_recipes.items is same as([]) %}
			<h4 class="mb-4" style="color: #4F805D">Community Recipes :</h4>
			<div class="d-flex justify-content-center flex-wrap">
				{% for recipe in public_recipes %}
					<div class="card text-white bg-success m-2" style="max-width: 18rem;">
						<div class="card-header">
							<h4 class="card-title">{{ recipe.name }}</h4>
						</div>
						<div class="card-body">
							<p class="card-text">{{ recipe.description }}
							</p>
						</div>
					</div>
				{% endfor %}
			</div>
			<div class="navigation d-flex justify-content-center mt-4">
				{{ knp_pagination_render(public_recipes) }}
			</div>
		{% endif %}
	</div>
{% endblock %}

templates/content/recipe/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Recipe -
	{{ recipe.name }}
{% endblock %}

{% block body %}
	<div class="container">
		{% for messages in app.flashes %}
			{% for message in messages %}
				<div class="alert alert-success mt-4">
					{{ message }}
				</div>
			{% endfor %}
		{% endfor %}
		<h1 class="mt-4">{{ recipe.name }}</h1>
		<div class="recipe_image">
			<img style="max-width:300px;" src="{{ vich_uploader_asset(recipe, 'imageFile') }}"/>
		</div>
		<span class="badge bg-danger">Rating :
			{{ (recipe.average|number_format(1, '.', ',')) }}
			/ 5</span>
		<div>
			<span class="badge bg-warning">Created at
				{{ recipe.createdAt | date('d/m/Y') }}
			</span>
		</div>
		<div class="mt-4">
			<p>Time :
				{% if recipe.time %}
					{{ recipe.time }}min
				{% else %}
					(unknown)
				{% endif %}
			</p>
		</div>
		<div class="mt-4">
			<p>Number of persons :
				{% if recipe.personNb %}
					{{ recipe.personNb }}
				{% else %}
					(unknown)
				{% endif %}
			</p>
		</div>
		<div class="mt-4">
			<p>Difficulty :
				{% if recipe.difficulty %}
					{{ recipe.difficulty }}
				{% else %}
					(unknown)
				{% endif %}
			</p>
		</div>
		<div>
			<p>Price :
				{{ recipe.price }}€</p>
		</div>
		<div>
			<p>Description :
				{{ recipe.description | raw }}</p>
		</div>

		<h5 style="color:#18bc9c">Ingredients for :</h5>
		{% for ingredient in recipe.ingredients %}
			<span class="badge bg-warning">{{ ingredient.name }}</span>
		{% endfor %}

		<div class='rate'>
			{{ form(form) }}
			</div>
		</div>
	{% endblock %}